'\" t
.\"     Title: w32dotool
.\"      Date: 2021-11-21
.\"    Manual: w32dotool Manual
.\"    Source: w32dotool 0.1
.\"  Language: English
.\"
.TH "W32DOTOOL" "1" "11/21/2021" "w32dotool 0\&.1" "w32dotool Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
w32dotool \- xdotool for Windows
.SH "SYNOPSIS"
.sp
w32dotool
.SH "OPTIONS"
.SH "TODO"
.sp
There is still lot of work to do\&. Please check our bugtracker for up\-to\-date information about tasks which are still not finished\&.
.sp
.SH "AUTHOR"
.sp
Richard Bäck
